#服务配置
server:
  port: 9001

#spring相关配置
spring:
  application:
    name: xiaonuo-eureka-app
  profiles:
    active: '@spring.active@'
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    locale: zh_CN
    serialization:
      # 格式化输出
      indent_output: false

